version: '3.1'

services:
  api-golang:
    build:
      context: .
    container_name: gopher-device
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: dcadmin
      DB_PASSWORD: dcadmin
      DB_NAME: dc_device
    depends_on:
      - postgres
      - pgadmin
    ports:
      - 8080:8080
    networks:
      - gopher

  postgres:
    container_name: db_postgres
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Usa el archivo init.sql para inicialización
    restart: unless-stopped
    labels:
      project: "golang"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dc_device
      POSTGRES_USER: dcadmin
      POSTGRES_PASSWORD: dcadmin
    networks:
      - gopher

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:latest
    container_name: devices_pgadmin
    restart: unless-stopped
    labels:
      project: "golang"
    ports:
      - "5010:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - gopher
# Volumen para PostgreSQL
volumes:
  postgres-data:
    driver: local

# Networks to be created to facilitate communication between containers
networks:
  gopher:
    driver: bridge
